title:        "Coding Tidbits"
tagline:      "Coding Tidbits"
url:          http://blog.cuberoot.in
markdown:     redcarpet
permalink:    /:title
pygments:     true
paginate:     5
excerpt_separator: "<!-- more -->"

disqus_short_name : cuberootblog
  
# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.

google_analytics_tracking_id : 'UA-37798927-2'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

