title:        "Coding Tidbits"
tagline:      "Coding Tidbits"
url:          http://blog.cuberoot.in
baseurl:      /
markdown:     kramdown
permalink:  /:title
highlighter:     rouge
paginate:     10
excerpt_separator: "<!-- more -->"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mr. Hyde"
      category: "project"


disqus_short_name : cuberootblog

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.

google_analytics_tracking_id : 'UA-37798927-2'

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

github_projects:
  -
    name: pluck_to_hash
    url : https://github.com/girishso/pluck_to_hash
  -
    name: Online Elm Repl
    url : https://github.com/girishso/elm-repl-in-browser
  -
    name: Indian Chess in Elm
    url : https://github.com/girishso/indian-chess
  -
    name: Your digital brain
    url : https://github.com/girishso/mindflowy

rubygems:
  -
    name: pluck_to_hash
    url : https://rubygems.org/gems/pluck_to_hash
  -
    name: spree-custom-notifications
    url : http://rubygems.org/gems/spree_custom_notifications
  -
    name: goog_currency
    url : http://rubygems.org/gems/goog_currency
  -
    name: rails-client-logger
    url : http://rubygems.org/gems/rails-client-logger
